name: Run Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 23
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'  # Use Eclipse Temurin (Adoptium)
          java-version: '23'
          cache: maven

      - name: Run Tests with Maven
        run: mvn test
